version: '2'
services:
  #PHP Endpoint
  app:
    image: enterprise:dev
    working_dir: /var/www
    volumes:
      - /var/www/public
      - /var/www/storage
      - shared-data:/web-data
    environment:
      QUEUE_DRIVER: database
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: db_platform
      DB_USERNAME: db_user
      DB_PASSWORD: db_password
  #Nginx Endpoint
  web:
    image: nginx:1.10-alpine
    ports:
      - 9091:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - shared-data:/var/www/
    working_dir: /var/www
  database:
    image: mdillon/postgis:10
    volumes:
      - dbdata:/var/lib/postgresql/postgresql/data
    environment:
       PGDATA: /var/lib/postgresql/postgresql/data
       POSTGRES_DB: db_platform
       POSTGRES_USER: db_user
       POSTGRES_PASSWORD: db_password
    ports:
      - "5432:5432"
volumes:
  dbdata:
  shared-data:
